// apps/web/src/lib/aliases.ts (aggiunte principali)
export type Canonical =
  | "EURUSD" | "GBPUSD" | "AUDUSD" | "NZDUSD" | "USDJPY" | "USDCHF" | "USDCAD"
  | "EURJPY" | "GBPJPY" | "AUDJPY" | "NZDJPY" | "CADJPY" | "EURNZD" | "AUDNZD" | "EURCAD" | "EURAUD"
  | "SPX" | "US100" | "DAX" | "US500" | "FTSEMIB" | "JP225"
  | "XAUUSD" | "XAGUSD" | "USOIL" | "NGAS" | "CORN" | "WHEAT" | "COFFEE" | "COCOA" | "SUGAR" | "SOYBEAN"
  | "US10Y"
  | "BTCUSD" | "ETHUSD"
  | "XPTUSD"
  | "DXY";

export const ALIAS_TO_CANONICAL: Record<string, Canonical> = {
  // Forex & crosses
  "EURUSD":"EURUSD","GBPUSD":"GBPUSD","AUDUSD":"AUDUSD","NZDUSD":"NZDUSD","USDJPY":"USDJPY","USDCHF":"USDCHF","USDCAD":"USDCAD",
  "EURJPY":"EURJPY","GBPJPY":"GBPJPY","AUDJPY":"AUDJPY","NZDJPY":"NZDJPY","CADJPY":"CADJPY","EURNZD":"EURNZD","AUDNZD":"AUDNZD","EURCAD":"EURCAD","EURAUD":"EURAUD",

  // Indici
  "SPX":"SPX","SPX500":"SPX","US500":"SPX","SPX500USD":"SPX",
  "US100":"US100","NAS100":"US100","NDX":"US100",
  "DAX":"DAX","GER40":"DAX",
  "FTSE MIB":"FTSEMIB","FTSEMIB":"FTSEMIB","IT40":"FTSEMIB",
  "US30":"US500","DJI":"US500","DOWJONES":"US500","US500CASH":"US500",
  "JP225":"JP225","NIKKEI":"JP225",

  // Commodities & metals
  "XAUUSD":"XAUUSD","GOLD":"XAUUSD",
  "XAGUSD":"XAGUSD","SILVER":"XAGUSD",
  "USOIL":"USOIL","WTI":"USOIL",
  "NGAS":"NGAS",
  "CORN":"CORN","WHEAT":"WHEAT","COFFEE":"COFFEE","COCOA":"COCOA","SUGAR":"SUGAR","SOYBEAN":"SOYBEAN",
  "XPTUSD":"XPTUSD",

  // Rates
  "US10Y":"US10Y",

  // Crypto
  "BTCUSD":"BTCUSD","BTC":"BTCUSD",
  "ETHUSD":"ETHUSD","ETH":"ETHUSD",

  // Dollar index
  "DXY":"DXY","USDIDX":"DXY","USDX":"DXY"
};
